Crop1/urls.py
from django.urls import path
from .views import index, predict_chances
app_name='Crop1'

urlpatterns=[
    path('', index, name='Crop1-name'),
    path('Crop1/',predict_chances,name='submit_prediction'),
    path('Crop1/results/',view_result,name='cresults'),
]

User/urls.py
from django.urls import path
from .views import user_view

urlpatterns=[
    path('',user_view,name='user-name')
]

fertilizer/urls.py
from django.urls import path
from .views import findex,predict_chances,view_results

app_name = "fertilizer"



urlpatterns=[
    path('', findex, name='fertilizer-name'),
    path('fertilizer/',predict_chances,name='submit_prediction'),
    path('fertilizer/results/',view_results,name='results'),
]

swobali/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fertilizer/', include('fertilizer.urls',namespace='fertilizer')),
    path('Crop1/', include('Crop1.urls', namespace='Crop1')),
    path('', include('User.urls')),
]

Crop1/models.py
from django.db import models

class CropResult(models.Model):
    Temperature=models.FloatField(blank=True)

    Humidity =models.FloatField(blank=True)


    Moisture = models.FloatField(blank=True)

    Stype =models.FloatField(blank=True)
    Ctype = models.FloatField(blank=True)
    Ph = models.FloatField(blank=True)

    classification = models.CharField(max_length =100)

User/models.py
from django.db import models

# Create your models here.

fertilizer/models.py
from django.db import models
from django.urls import reverse


class FreResults(models.Model):
    Temperature=models.FloatField(blank=True)

    Humidity =models.FloatField(blank=True)


    Moisture = models.FloatField(blank=True)

    Stype =models.FloatField(blank=True)
    Ctype = models.FloatField(blank=True)
    Nitrogen = models.FloatField(blank=True)
    Potassium = models.FloatField(blank=True)
    Phosphorous= models.FloatField(blank=True)

    classification = models.CharField(max_length =100)


    def get_absolute_url(self):
        return reverse("fertilizer",kwargs={"id":self.id})




    def __str__(self):
          return self.classification

Crop1/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse

import pandas as pd
from django.urls import reverse
#from .models import CropResults

def index(request):

    context={'name':'Crop'}

    # return HttpResponseRedirect(reverse("Crop1:submit_prediction"))
    context.update({'crop_url': reverse("Crop1:submit_prediction")})
    return render(request,'Crop1/index.html',context)



def predict_chances(request):

    if request.POST.get('action') == 'post':

        # Receive data from client
        Temperature= float(request.POST.get('Temperature'))
        Humidity = float(request.POST.get('Humidity'))

        Moisture = float(request.POST.get('Moisture'))

        Stype =float(request.POST.get('Stype'))
        Ph = float(request.POST.get('Ph'))




        # Unpickle model
        import pickle
        model = pd.read_pickle(r"C:\Users\dell\Desktop\new_model1.pickle")


        # Make prediction
        result = model.predict([[Stype, Ph, Temperature, Humidity, Moisture]])

        classification = result[0]

        return JsonResponse({'result': classification,'Stype':Stype, 'Ph':Ph,'Temperature':Temperature,'Humidity':Humidity,'Moisture':Moisture },
                            safe=False)


def view_result(request):

       data={"dataset": CropResults.objects.all()}
       return render(request,'Crop1/result.html',data)

User/views.py
from django.shortcuts import render


def user_view(request):
    return render(request,'User/index.html')

fertilizer/views.py
from django.http import JsonResponse
from django.shortcuts import render
import pandas as pd
from .models import FreResults



def findex(request):
    context={'name':'fertilizer'}
    return render(request,'fertilizer/index.html',context)


def predict_chances(request):

    if request.POST.get('action') == 'post':

        # Receive data from client
        Temperature= float(request.POST.get('Temperature'))
        Humidity = float(request.POST.get('Humidity'))

        Moisture = float(request.POST.get('Moisture'))

        Stype =float(request.POST.get('Stype'))
        Ctype = float(request.POST.get('Ctype'))
        Nitrogen = float(request.POST.get('Nitrogen'))
        Potassium = float(request.POST.get('Potassium'))
        Phosphorous = float(request.POST.get('Phosphorous'))




        # Unpickle model
        import pickle
        model = pd.read_pickle(r"C:\Users\dell\Desktop\new_model.pickle")


        # Make prediction
        result = model.predict([[Stype, Ctype, Temperature, Humidity, Moisture, Potassium, Phosphorous, Nitrogen]])

        classification = result[0]

        FreResults.objects.create(Stype=Stype, Ctype=Ctype,Temperature=Temperature,Humidity=Humidity,Moisture=Moisture,Potassium=Potassium,Phosphorous=Phosphorous,Nitrogen=Nitrogen,classification=classification)


        return JsonResponse({'result': classification,'Stype':Stype, 'Ctype':Ctype,'Temperature':Temperature,'Humidity':Humidity,'Moisture':Moisture,'Potassium':Potassium,'Phosphorous':Phosphorous,'Nitrogen':Nitrogen },
                            safe=False)

def view_results(request):
    data={"dataset": FreResults.objects.all()}
    return render(request,'fertilizer/result.html',data)

templates/Crop1/index.html
{% extends "master/base2.html" %}

{% block main %}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" >
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel" style="color:#026440;">Here is the result </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5 style="color:#026440;">Prediction Input:</h5>
                <div style="color:#026440;">Temperature: <span id="tm"></span></div>
                <div style="color:#026440;">Humidity: <span id="hu"></span></div>
                <div style="color:#026440;">Moisture: <span id="ms"></span></div>
                <div style="color:#026440;">Soil Type: <span id="st"></span></div>

                <div style="color:#026440;">pH: <span id="p"></span></div>
                <h5 class="pt-3" style="color:#026440;">Best Crop:</h5>
                <div id="prediction"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>


            </div>
        </div>
    </div>
</div>

<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-4">

            <h3 style="color:#026440;">Predict Best Crop</h3>
            <br>
            <br>
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                   <div class="form-group" style="color:#037d50;">
                    <label for="tempareture"><b>Temperature</b></label>
                    <input type="number" step="0.1"  class="form-control" id="Temperature" placeholder="" required>
                </div>
                <div class="form-group"  style="color:#037d50;">
                    <label for="humidity"><b>Humidity</b></label>
                    <input type="number" step="0.1" class="form-control" id="Humidity" placeholder="" required>
                </div>
                <div class="form-group"  style="color:#037d50;">
                    <label for="moisture"><b>Moisture</b></label>
                    <input type="number" step="0.1" class="form-control" id="Moisture" placeholder="" required>
                </div>


                <div class="form-group">
                    <label for="soiltype" style="color:#026440;"><b>Soil Type</b></label>
                    <select name="soiltype" class="form-control" id="Stype" placeholder="" required>

                        <option value="1">Black</option>
                        <option value="2">Clayey</option>
                        <option value="3">Loamy</option>
                        <option value="4">Red</option>
                         <option value="5">Sandy</option>

                    </select>
                </div>
                <div class="form-group">
                    <label for="ph" style="color:#026440;"><b>pH</b></label>
                    <select name="ph" class="form-control" id="Ph" placeholder="" required style="color:#026440;">

                      <option value="1">Extremely acidic</option>
                         <option value="2">Moderately acidic</option>
                          <option value="3">Moderately alkaline</option>
                        <option value="4">Slightly acidic</option>
                         <option value="5">Slightly alkaline</option>
                        <option value="6">Strongly acidic</option>
                         <option value="7">Strongly alkaline</option>
                        <option value="8">Very strongly acidic</option>
                         <option value="9">Neutral</option>
                        <option value="10">Very strongly alkaline</option>


                    </select>

                </div>
                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal"  style="background-color:#026440;" data-target="#exampleModal">Submit</button>
                </div>
            </form>

        </div>
    </div>
</div>




    <script>


     var crop_url = '{{crop_url}}';
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',

              url:crop_url,
            data:{
                Temperature:$('#Temperature').val(),
                Humidity:$('#Humidity').val(),
                Moisture:$('#Moisture').val(),
                Stype:$('#Stype').val(),
                Ph:$('#Ph').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"].reset();
                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("tm").innerHTML = json['Temperature']
                document.getElementById("hu").innerHTML = json['Humidity']
                document.getElementById("ms").innerHTML = json['Moisture']
                document.getElementById("st").innerHTML = json['Stype']
                document.getElementById("p").innerHTML = json['Ph']


            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>
{% endblock %}

templates/Crop1/result.html
{% extends "master/base2.html" %}


{% block main %}
    <div class="container pt-5">
        <div class="row">

        <h1> Crop Prediction Results:</h1>

            <table class="table" style="background-color:#99d7b5">
                <thead>
                <tr>
                <th scope="col">#</th>
                      <th scope="col">Temperature</th>
                <th scope="col">Humidity</th>
                <th scope="col">Moisture</th>
                    <th scope="col">Soil Type</th>
                <th scope="col">pH</th>

                <th scope="col">Predicted Crop</th>
                </tr>
                </thead>
                <tbody>
                {% for data in dataset %}
                    <tr>
                    <th scope="row">{{ data.id }}</th>
                    <td>{{ data.Temperature }}</td>
                    <td>{{ data.Humidity }}</td>
                    <td>{{ data.Moisture }}</td>
                    <td>{{ data.Stype }}</td>
                    <td>{{ data.Ph}}</td>
                        <td>{{ data.classification }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/fertilizer/index.html
{% extends "master/base.html" %}

{% block main %}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"  style="color:#026440;">Prediction Results</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="color:#026440;">
                <h5>Prediction Input:</h5>
                <div>Temperature: <span id="tm"></span></div>
                <div>Humidity: <span id="hu"></span></div>
                <div>Moisture: <span id="ms"></span></div>
                <div>Soil Type: <span id="st"></span></div>
                <div>Crop Type: <span id="ct"></span></div>
                <div>Nitrogen: <span id="n"></span></div>
                <div>Potassium: <span id="k"></span></div>
                <div>Phosphorous: <span id="p"></span></div>
                <h5 class="pt-3">Best Fertilizer:</h5>
                <div id="prediction"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

            </div>
        </div>
    </div>
</div>

<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-4">

            <h3 style="color:#026440;">Fertilizer Prediction</h3>
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group" style="color:#037d50;">
                    <label for="tempreture"><b>Temperature</b></label>
                    <input type="number" step="0.1"  class="form-control" id="Temperature" placeholder="" required>
                </div>
                <div class="form-group"  style="color:#037d50;">
                    <label for="humidity"><b>Humidity</b></label>
                    <input type="number" step="0.1" class="form-control" id="Humidity" placeholder="" required>
                </div>
                <div class="form-group"  style="color:#037d50;">
                    <label for="moisture"><b>Moisture</b></label>
                    <input type="number" step="0.1" class="form-control" id="Moisture" placeholder="" required>
                </div>


                <div class="form-group"  style="color:#037d50;">
                    <label for="soiltype"><b>Soil Type</b></label>
                    <select name="soiltype" class="form-control" id="Stype" placeholder="" required  style="color:#037d50;">

                        <option value="1">Black</option>
                        <option value="2">Clayey</option>
                        <option value="3">Loamy</option>
                        <option value="4">Red</option>
                         <option value="5">Sandy</option>

                    </select>
                </div>
                <div class="form-group" style="color:#037d50;">
                    <label for="croptype"><b>Crop Type</b></label>
                    <select name="croptype" class="form-control" id="Ctype" placeholder="" required  style="color:#037d50;">

                        <option value="1">Barley</option>
                         <option value="2">Cotton</option>
                          <option value="3">Ground Nuts</option>
                        <option value="4">Maize</option>
                         <option value="5">Millets</option>
                        <option value="6">Oil Seeds</option>
                         <option value="7">Paddy</option>
                        <option value="8">Pulses</option>
                         <option value="9">Sugarcane</option>
                        <option value="10">Tobacco</option>
                         <option value="11">Wheat</option>


                    </select>

                </div>
                <div class="form-group"  style="color:#037d50;">
                    <label for="nitrogen"><b>Nitrogen</b></label>
                    <input type="number" step="0.1" class="form-control" id="Nitrogen" placeholder="" required>
                </div>
                <div class="form-group"  style="color:#037d50;">
                    <label for="potassium"><b>Potassium</b></label>
                    <input type="number" step="0.1" class="form-control" id="Potassium" placeholder="" required>
                </div>
                <div class="form-group"  style="color:#037d50;">
                    <label for="phosphorous"><b>Phosphorous</b></label>
                    <input type="number" step="0.1" class="form-control" id="Phosphorous" placeholder="" required>
                </div>
                <button type="submit" value="Submit" class="btn btn-primary" style="background-color:#026440;" data-toggle="modal" data-target="#exampleModal">Submit</button>
            </form>
        </div>
    </div>
</div>




    <script>

    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "fertilizer:submit_prediction" %}',
            data:{
                Temperature:$('#Temperature').val(),
                Humidity:$('#Humidity').val(),
                Moisture:$('#Moisture').val(),
                Stype:$('#Stype').val(),
                Ctype:$('#Ctype').val(),
                Nitrogen:$('#Nitrogen').val(),
                Potassium:$('#Potassium').val(),
                Phosphorous:$('#Phosphorous').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"].reset();
                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("tm").innerHTML = json['Temperature']
                document.getElementById("hu").innerHTML = json['Humidity']
                document.getElementById("ms").innerHTML = json['Moisture']
                document.getElementById("st").innerHTML = json['Stype']
                document.getElementById("ct").innerHTML = json['Ctype']
                document.getElementById("n").innerHTML = json['Nitrogen']
                document.getElementById("k").innerHTML = json['Potassium']
                document.getElementById("p").innerHTML = json['Phosphorous']

            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>
{% endblock %}

templates/fertilizer/result.html
{% extends "master/base.html" %}


{% block main %}
    <div class="container pt-5">
        <div class="row">

        <h1> Fertilizer Prediction Results:</h1>

            <table class="table" style="background-color:#99d7b5">
                <thead>
                <tr>
                <th scope="col">#</th>
                      <th scope="col">Temperature</th>
                <th scope="col">Humidity</th>
                <th scope="col">Moisture</th>
                    <th scope="col">Soil Type</th>
                <th scope="col">Crop Type</th>
                <th scope="col">Nitrogen</th>
                <th scope="col">Potassium</th>
                <th scope="col">Phosphorous</th>
                <th scope="col">Predicted Fertilizer</th>
                </tr>
                </thead>
                <tbody>
                {% for data in dataset %}
                    <tr>
                    <th scope="row">{{ data.id }}</th>
                    <td>{{ data.Temperature }}</td>
                    <td>{{ data.Humidity }}</td>
                    <td>{{ data.Moisture }}</td>
                    <td>{{ data.Stype }}</td>
                    <td>{{ data.Ctype }}</td>
                    <td>{{ data.Nitrogen }}</td>
                    <td>{{ data.Potassium }}</td>
                    <td>{{ data.Phosphorous }}</td>
                        <td>{{ data.classification }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/master/base.html
{% load static %}
<html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title> prediction</title>
        <script>
            {% block css %}
            {% endblock %}
        </script>
    </head>
    <body>


    <nav class="navbar navbar-expand-lg navbar-dark bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <div class="container">
                <!-- Start Header Navigation -->
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-menu" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
                    <a class="navbar-brand" href="index.html"><img src="{% static 'images/swobalilogo.png' %}" class="logo" alt="" height="80px" width="auto"></a>
                </div>

            <ul class="nav navbar-nav navbar-right">
                <li >
                    <button type="submit">

                    <a href="fertilizer/results" style="color:#026440;" ><b>DataBase</b></a>
                        </button>

                </li>
                <li>
                     <button type="submit">

                    <a href=" {% url 'user-name' %}" style="color:#026440;"><b>Back</b></a>
                     </button>

                </li>
            </ul>
        </div>
        </div>
    </nav>

    {% block main %}
    {% endblock %}
    <footer class="container">
    <p class="float-right" >

        <a href="#">Back to top</a>
        </p>
    <p>© 2021 Swobali, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
  </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

templates/master/base2.html
{% load static %}
<html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title> prediction</title>
        <script>
            {% block css %}
            {% endblock %}
        </script>
    </head>
    <body>


        <header class="main-header">
        <!-- Start Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light  bg-light navbar-default bootsnav">
            <div class="container">
                <!-- Start Header Navigation -->
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-menu" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
                    <a class="navbar-brand" href="index.html"><img src="{% static 'images/swobalilogo.png' %}" class="logo" alt="" height="80px" width="auto"></a>
                </div>
                <!-- End Header Navigation -->

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="navbar-menu">
                    <ul class="nav navbar-nav ml-auto" data-in="fadeInDown" data-out="fadeOutUp">


                        <li class="nav-item">
                            <button>
                                <a class="nav-link" href="{% url 'user-name'  %}" style="color:#026440;"><b>Back</b></a>
                            </button>
                        </li>

                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
        </nav>
        <!-- End Navigation -->
    </header>
    {% block main %}
    {% endblock %}
    <footer class="container">
    <p class="float-right">

        <a href="#">Back to top</a>
        </p>
    <p>© 2021-2022 Swobali, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
  </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>